version: '3'
services:
  todo: 
    build: .
    command: gunicorn --workers=3 -b 0.0.0.0:8000 app:app
    ports:
      - "8000"
    volumes:
      - TODO_VOLUME:/app
      - ./static:/app/static
      - ./templates:/app/templates
    scale: 5
    

  nginx:
    image: nginx:1.23
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo
    ports:
      - "80:80"

volumes:
  TODO_VOLUME:

